import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';
import '../../themes/app_theme.dart';

class LearnDetailScreen extends StatelessWidget {
  final String topic;

  const LearnDetailScreen({super.key, required this.topic});

  @override
  Widget build(BuildContext context) {
    final blocks = switch (topic) {
      'Trending Courses' => _trendingCourses(context),
      'Architecture' => _architectureCourses(context),
      'Management' => _managementCourses(context),
      'Maths and Science' => _mathsScienceCourses(context),
      'Law' => _lawCourses(context),
      'Government Exam Preparation' => _govExamCourses(context),
      _ => _csCourses(context),
    };

    return Scaffold(
      appBar: AppBar(
        title: Text(topic),
        backgroundColor: AppColors.primaryBlue,
        elevation: 0,
      ),
      body: Container(
        decoration: const BoxDecoration(
          gradient: LinearGradient(
            colors: [AppColors.primaryBlue, AppColors.tealBlue],
            begin: Alignment.topCenter,
            end: Alignment.bottomCenter,
          ),
        ),
        child: ListView(
          padding: const EdgeInsets.all(20),
          children: blocks,
        ),
      ),
    );
  }

  List<Widget> _csCourses(BuildContext context) => [
        const Text(
          '🔥 Top courses with YouTube playlists in English & Tamil',
          style: TextStyle(
            color: Colors.white,
            fontSize: 16,
            fontWeight: FontWeight.bold,
          ),
        ),
        const SizedBox(height: 16),
        _buildCourseBlock(
          context,
          number: '1️⃣',
          title: 'Full Computer Science Basics',
          englishTitle: 'Harvard University CS50',
          englishUrl: 'https://www.youtube.com/@cs50/playlists',
          tamilTitle: 'GUVI (Tamil tech courses)',
          tamilUrl: 'https://www.youtube.com/@GUVI/playlists',
          notes: 'Programming basics, logic building',
        ),
        _buildCourseBlock(
          context,
          number: '2️⃣',
          title: 'Programming (Java / Python)',
          englishTitle: 'freeCodeCamp',
          englishUrl: 'https://www.youtube.com/@freecodecamp/playlists',
          tamilTitle: 'Tamil Developer',
          tamilUrl: 'https://www.youtube.com/@TamilDeveloper/playlists',
          notes: 'Best for beginners',
        ),
        _buildCourseBlock(
          context,
          number: '3️⃣',
          title: 'Data Structures & Algorithms',
          englishTitle: 'take U forward',
          englishUrl: 'https://www.youtube.com/@takeUforward/playlists',
          tamilTitle: 'Code IO Tamil',
          tamilUrl: 'https://www.youtube.com/@CodeIOTamil/playlists',
          notes: 'Needed for interviews and placements',
        ),
        _buildCourseBlock(
          context,
          number: '4️⃣',
          title: 'Web Development',
          englishTitle: 'The Net Ninja',
          englishUrl: 'https://www.youtube.com/@NetNinja/playlists',
          tamilTitle: 'Error Makes Clever',
          tamilUrl: 'https://www.youtube.com/@ErrorMakesClever/playlists',
          notes: 'Covers HTML, CSS, JS',
        ),
        _buildCourseBlock(
          context,
          number: '5️⃣',
          title: 'Core Subjects (DBMS, OS, CN)',
          englishTitle: 'Neso Academy',
          englishUrl: 'https://www.youtube.com/@nesoacademy/playlists',
          tamilTitle: 'Gate Smashers (English/Hindi mix)',
          tamilUrl: 'https://www.youtube.com/@GateSmashers/playlists',
          notes: 'Important for interviews and exams',
        ),
        _buildCourseBlock(
          context,
          number: '6️⃣',
          title: 'Flutter (Your Main Goal 🚀)',
          englishTitle: 'Flutter',
          englishUrl: 'https://www.youtube.com/@flutterdev/playlists',
          tamilTitle: 'Flutter Tamil',
          tamilUrl: 'https://www.youtube.com/@FlutterTamil/playlists',
          notes: 'Focus here for your job',
        ),
        _buildCourseBlock(
          context,
          number: '7️⃣',
          title: 'Projects & Real Apps',
          englishTitle: 'freeCodeCamp Projects',
          englishUrl: 'https://www.youtube.com/@freecodecamp/playlists',
          tamilTitle: 'Tamil Coding',
          tamilUrl: 'https://www.youtube.com/@TamilCoding/playlists',
          notes: 'Build portfolio',
        ),
      ];

  List<Widget> _trendingCourses(BuildContext context) => [
        const Text(
          '🚀 Trending Tech Courses (YouTube playlists)',
          style: TextStyle(
            color: Colors.white,
            fontSize: 16,
            fontWeight: FontWeight.bold,
          ),
        ),
        const SizedBox(height: 16),
        _buildCourseBlock(
          context,
          number: '1️⃣',
          title: 'Electric Vehicles (EV)',
          englishTitle: 'GreatScott! (EV electronics & batteries)',
          englishUrl: 'https://www.youtube.com/@greatscottlab/playlists',
          tamilTitle: 'EV Tech Tamil (EV basics in Tamil)',
          tamilUrl: 'https://www.youtube.com/@EVTechTamil/playlists',
          notes: 'Battery, BMS, motors, charging',
        ),
        _buildCourseBlock(
          context,
          number: '2️⃣',
          title: 'Blockchain & Web3',
          englishTitle: 'EatTheBlocks',
          englishUrl: 'https://www.youtube.com/@EatTheBlocks/playlists',
          tamilTitle: 'Codevolution (clear English; Tamil subs available)',
          tamilUrl: 'https://www.youtube.com/@Codevolution/playlists',
          notes: 'Solidity, smart contracts, DApps',
        ),
        _buildCourseBlock(
          context,
          number: '3️⃣',
          title: 'Cyber Security',
          englishTitle: 'NetworkChuck',
          englishUrl: 'https://www.youtube.com/@NetworkChuck/playlists',
          tamilTitle: 'Cyber Tamizha',
          tamilUrl: 'https://www.youtube.com/@CyberTamizha/playlists',
          notes: 'Ethical hacking, networking, blue team basics',
        ),
        _buildCourseBlock(
          context,
          number: '4️⃣',
          title: 'Gen AI & LLMs',
          englishTitle: 'AssemblyAI',
          englishUrl: 'https://www.youtube.com/@AssemblyAI/playlists',
          tamilTitle: 'AI Tamil (intro to AI/ML in Tamil)',
          tamilUrl: 'https://www.youtube.com/@AITamil/playlists',
          notes: 'Transformers, prompt engineering basics',
        ),
        _buildCourseBlock(
          context,
          number: '5️⃣',
          title: 'Cloud & DevOps',
          englishTitle: 'TechWorld with Nana',
          englishUrl: 'https://www.youtube.com/@TechWorldwithNana/playlists',
          tamilTitle: 'Karthik DevOps Tamil',
          tamilUrl: 'https://www.youtube.com/@karthikdevops/playlists',
          notes: 'Docker, Kubernetes, CI/CD',
        ),
        _buildCourseBlock(
          context,
          number: '6️⃣',
          title: 'Data Engineering',
          englishTitle: 'Seattle Data Guy',
          englishUrl: 'https://www.youtube.com/@SeattleDataGuy/playlists',
          tamilTitle: 'Data Engineering Tamil',
          tamilUrl: 'https://www.youtube.com/@DataEngineeringTamil/playlists',
          notes: 'Pipelines, ETL, warehouses',
        ),
        _buildCourseBlock(
          context,
          number: '7️⃣',
          title: 'AR/VR & XR',
          englishTitle: 'Brackeys (Unity basics archived)',
          englishUrl: 'https://www.youtube.com/@Brackeys/playlists',
          tamilTitle: 'Tamil Gaming / Unity Tamil',
          tamilUrl: 'https://www.youtube.com/@TamilGaming/playlists',
          notes: 'Unity, game/AR foundations',
        ),
        _buildCourseBlock(
          context,
          number: '8️⃣',
          title: 'UI/UX & Product Design',
          englishTitle: 'DesignCourse',
          englishUrl: 'https://www.youtube.com/@DesignCourse/playlists',
          tamilTitle: 'UX Tamil',
          tamilUrl: 'https://www.youtube.com/@UXTamil/playlists',
          notes: 'Figma, research, usability',
        ),
        _buildCourseBlock(
          context,
          number: '9️⃣',
          title: 'Mobile Dev (Flutter/Kotlin)',
          englishTitle: 'Flutter',
          englishUrl: 'https://www.youtube.com/@flutterdev/playlists',
          tamilTitle: 'Flutter Tamil',
          tamilUrl: 'https://www.youtube.com/@FlutterTamil/playlists',
          notes: 'Cross-platform apps',
        ),
        _buildCourseBlock(
          context,
          number: '🔟',
          title: 'Product Management Tech',
          englishTitle: 'Product School',
          englishUrl: 'https://www.youtube.com/@ProductSchool/playlists',
          tamilTitle: 'Tamil Startup & PM (mixed)',
          tamilUrl: 'https://www.youtube.com/@StartupTamil/playlists',
          notes: 'Roadmaps, metrics, stakeholder mgmt.',
        ),
      ];

  List<Widget> _architectureCourses(BuildContext context) => [
        const Text(
          '🏛️ Architecture Courses (YouTube playlists)',
          style: TextStyle(
            color: Colors.white,
            fontSize: 16,
            fontWeight: FontWeight.bold,
          ),
        ),
        const SizedBox(height: 16),
        _buildCourseBlock(
          context,
          number: '1️⃣',
          title: 'Architecture Fundamentals',
          englishTitle: 'MIT Architecture',
          englishUrl: 'https://www.youtube.com/@MITarchitecture/playlists',
          tamilTitle: 'Tamil Architecture Basics',
          tamilUrl: 'https://www.youtube.com/@TamilArchitecture/playlists',
          notes: 'Design principles, history, basics',
        ),
        _buildCourseBlock(
          context,
          number: '2️⃣',
          title: 'AutoCAD & Drafting',
          englishTitle: 'SourceCAD',
          englishUrl: 'https://www.youtube.com/@SourceCAD/playlists',
          tamilTitle: 'AutoCAD Tamil',
          tamilUrl: 'https://www.youtube.com/@AutoCADTamil/playlists',
          notes: '2D/3D drafting essentials',
        ),
        _buildCourseBlock(
          context,
          number: '3️⃣',
          title: 'Revit & BIM',
          englishTitle: 'Balkan Architect',
          englishUrl: 'https://www.youtube.com/@BalkanArchitect/playlists',
          tamilTitle: 'Revit Tamil',
          tamilUrl: 'https://www.youtube.com/@RevitTamil/playlists',
          notes: 'BIM workflows, families, sheets',
        ),
        _buildCourseBlock(
          context,
          number: '4️⃣',
          title: 'Structural Basics',
          englishTitle: 'StructureFree',
          englishUrl: 'https://www.youtube.com/@Structurefree/playlists',
          tamilTitle: 'Civil/Structural Tamil',
          tamilUrl: 'https://www.youtube.com/@civilgnan/playlists',
          notes: 'Statics, loads, materials',
        ),
        _buildCourseBlock(
          context,
          number: '5️⃣',
          title: 'Sustainable Design',
          englishTitle: 'Architecture Academy',
          englishUrl: 'https://www.youtube.com/@TheArchitectureAcademy/playlists',
          tamilTitle: 'Green Building Tamil',
          tamilUrl: 'https://www.youtube.com/@GreenBuildingTamil/playlists',
          notes: 'Climate, materials, ratings (LEED/Griha basics)',
        ),
      ];

  List<Widget> _managementCourses(BuildContext context) => [
        const Text(
          '📈 Management & Business Courses (YouTube playlists)',
          style: TextStyle(
            color: Colors.white,
            fontSize: 16,
            fontWeight: FontWeight.bold,
          ),
        ),
        const SizedBox(height: 16),
        _buildCourseBlock(
          context,
          number: '1️⃣',
          title: 'MBA Core (Finance/Marketing/Strategy)',
          englishTitle: 'MIT Sloan / Stanford GSB talks',
          englishUrl: 'https://www.youtube.com/@mitsloan/playlists',
          tamilTitle: 'Tamil Business School',
          tamilUrl: 'https://www.youtube.com/@TamilBusinessSchool/playlists',
          notes: 'Case-style lectures and talks',
        ),
        _buildCourseBlock(
          context,
          number: '2️⃣',
          title: 'Project Management',
          englishTitle: 'Project Management Institute',
          englishUrl: 'https://www.youtube.com/@pmi/playlists',
          tamilTitle: 'PM Tamil (PMP basics)',
          tamilUrl: 'https://www.youtube.com/@PMTamil/playlists',
          notes: 'PMP/Agile foundations',
        ),
        _buildCourseBlock(
          context,
          number: '3️⃣',
          title: 'Product Management',
          englishTitle: 'Product School',
          englishUrl: 'https://www.youtube.com/@ProductSchool/playlists',
          tamilTitle: 'Product Tamil',
          tamilUrl: 'https://www.youtube.com/@ProductTamil/playlists',
          notes: 'Roadmaps, metrics, stakeholder mgmt.',
        ),
        _buildCourseBlock(
          context,
          number: '4️⃣',
          title: 'Leadership & Communication',
          englishTitle: 'Leadership Nudge',
          englishUrl: 'https://www.youtube.com/@LeadershipNudge/playlists',
          tamilTitle: 'Communication Skills Tamil',
          tamilUrl: 'https://www.youtube.com/@commTamil/playlists',
          notes: 'Team leading, presentations, feedback',
        ),
        _buildCourseBlock(
          context,
          number: '5️⃣',
          title: 'Entrepreneurship & Startups',
          englishTitle: 'Y Combinator',
          englishUrl: 'https://www.youtube.com/@ycombinator/playlists',
          tamilTitle: 'Startup Tamil',
          tamilUrl: 'https://www.youtube.com/@StartupTamil/playlists',
          notes: 'Fundamentals of building products/business',
        ),
      ];

  List<Widget> _mathsScienceCourses(BuildContext context) => [
        const Text(
          '🧮 Maths, Aptitude & Science (YouTube playlists)',
          style: TextStyle(
            color: Colors.white,
            fontSize: 16,
            fontWeight: FontWeight.bold,
          ),
        ),
        const SizedBox(height: 16),
        _buildCourseBlock(
          context,
          number: '1️⃣',
          title: 'Quantitative Aptitude (placements, govt exams)',
          englishTitle: 'Talent Battle – Aptitude',
          englishUrl: 'https://www.youtube.com/@TalentBattle/playlists',
          tamilTitle: 'Feel Free to Learn – Aptitude (Tamil)',
          tamilUrl: 'https://www.youtube.com/@FeelFreetoLearn/playlists',
          notes: 'Arithmetic, percentages, ratios, time & work, DI',
        ),
        _buildCourseBlock(
          context,
          number: '2️⃣',
          title: 'Reasoning & Puzzles',
          englishTitle: 'Unacademy Verbal & Reasoning',
          englishUrl: 'https://www.youtube.com/@unacademyverbal/playlists',
          tamilTitle: 'Verbal Reasoning Tamil (Feel Free to Learn)',
          tamilUrl: 'https://www.youtube.com/@FeelFreetoLearn/playlists',
          notes: 'Logical, verbal, non-verbal reasoning',
        ),
        _buildCourseBlock(
          context,
          number: '3️⃣',
          title: 'Core Mathematics Refresher',
          englishTitle: 'PatrickJMT / 3Blue1Brown (concepts)',
          englishUrl: 'https://www.youtube.com/@3blue1brown/playlists',
          tamilTitle: 'Maths in Tamil (VEATHA / Feel Free to Learn)',
          tamilUrl: 'https://www.youtube.com/@VEATHA/playlists',
          notes: 'Algebra, calculus intuition, linear algebra basics',
        ),
        _buildCourseBlock(
          context,
          number: '4️⃣',
          title: 'Engineering Maths for GATE/CAT',
          englishTitle: 'NPTEL / Gate Smashers Maths',
          englishUrl: 'https://www.youtube.com/@GateSmashers/playlists',
          tamilTitle: 'GATE Maths Tamil',
          tamilUrl: 'https://www.youtube.com/@GATEMathsTamil/playlists',
          notes: 'Probability, statistics, calculus, transforms',
        ),
        _buildCourseBlock(
          context,
          number: '5️⃣',
          title: 'Data Interpretation & Analysis',
          englishTitle: 'BYJU’S Exam Prep DI',
          englishUrl: 'https://www.youtube.com/@byjusexamprep/playlists',
          tamilTitle: 'DI in Tamil (FFTL Aptitude)',
          tamilUrl: 'https://www.youtube.com/@FeelFreetoLearn/playlists',
          notes: 'Graphs, tables, caselets for exams/interviews',
        ),
        _buildCourseBlock(
          context,
          number: '6️⃣',
          title: 'Science Fundamentals',
          englishTitle: 'CrashCourse Science',
          englishUrl: 'https://www.youtube.com/@crashcourse/playlists',
          tamilTitle: 'Science Tamil (Ariviyal in Tamil)',
          tamilUrl: 'https://www.youtube.com/@ariviyalintamil/playlists',
          notes: 'Physics/Chem/Bio refreshers for understanding tech',
        ),
      ];

  List<Widget> _lawCourses(BuildContext context) => [
        const Text(
          '⚖️ Law & Competitive Exams (YouTube playlists)',
          style: TextStyle(
            color: Colors.white,
            fontSize: 16,
            fontWeight: FontWeight.bold,
          ),
        ),
        const SizedBox(height: 16),
        _buildCourseBlock(
          context,
          number: '1️⃣',
          title: 'Indian Constitution & Polity',
          englishTitle: 'Study IQ Polity',
          englishUrl: 'https://www.youtube.com/@StudyIQeducation/playlists',
          tamilTitle: 'Polity Tamil (FFTL / IAS Tamil)',
          tamilUrl: 'https://www.youtube.com/@IASTamil/playlists',
          notes: 'Fundamentals for judiciary/UPSC/State PSC',
        ),
        _buildCourseBlock(
          context,
          number: '2️⃣',
          title: 'Bare Acts & Case Law Basics',
          englishTitle: 'LegalEdge by Toprankers',
          englishUrl: 'https://www.youtube.com/@LegalEdge/playlists',
          tamilTitle: 'Law Tamil (basic acts explanations)',
          tamilUrl: 'https://www.youtube.com/@LawTamil/playlists',
          notes: 'IPC, CrPC, Evidence overview',
        ),
        _buildCourseBlock(
          context,
          number: '3️⃣',
          title: 'Judiciary Prep (Lower/State)',
          englishTitle: 'Unacademy Judiciary',
          englishUrl: 'https://www.youtube.com/@unacademyjudiciary/playlists',
          tamilTitle: 'Judiciary Tamil (basics & Q/A)',
          tamilUrl: 'https://www.youtube.com/@JudiciaryTamil/playlists',
          notes: 'MCQs, past questions, judgment writing',
        ),
        _buildCourseBlock(
          context,
          number: '4️⃣',
          title: 'CLAT / AILET / Law Entrance',
          englishTitle: 'CLAT Possible',
          englishUrl: 'https://www.youtube.com/@CLATPossible/playlists',
          tamilTitle: 'CLAT Tamil (aptitude + legal)',
          tamilUrl: 'https://www.youtube.com/@CLATTamil/playlists',
          notes: 'Legal reasoning, GK, English, logical reasoning',
        ),
        _buildCourseBlock(
          context,
          number: '5️⃣',
          title: 'Legal Drafting & Contracts',
          englishTitle: 'LawSikho Drafting',
          englishUrl: 'https://www.youtube.com/@LawSikho/playlists',
          tamilTitle: 'Contract Basics Tamil',
          tamilUrl: 'https://www.youtube.com/@ContractLawTamil/playlists',
          notes: 'Agreements, notices, essentials',
        ),
        _buildCourseBlock(
          context,
          number: '6️⃣',
          title: 'Forensics & Cyber Law',
          englishTitle: 'Cyber Law India (Basics)',
          englishUrl: 'https://www.youtube.com/@CyberLawIndia/playlists',
          tamilTitle: 'Cyber Law Tamil',
          tamilUrl: 'https://www.youtube.com/@CyberLawTamil/playlists',
          notes: 'IT Act, evidence in digital crimes',
        ),
      ];

  List<Widget> _govExamCourses(BuildContext context) => [
        const Text(
          '🏛️ Govt Exam Prep (Tamil Nadu & Central) – YouTube playlists',
          style: TextStyle(
            color: Colors.white,
            fontSize: 16,
            fontWeight: FontWeight.bold,
          ),
        ),
        const SizedBox(height: 16),
        _buildCourseBlock(
          context,
          number: '1️⃣',
          title: 'TNPSC Group 1/2/4',
          englishTitle: 'We Shine Academy (English/Tamil mix)',
          englishUrl: 'https://www.youtube.com/@weshineacademy/playlists',
          tamilTitle: 'Feel Free to Learn – TNPSC',
          tamilUrl: 'https://www.youtube.com/@FeelFreetoLearn/playlists',
          notes: 'Aptitude, polity, history, current affairs',
        ),
        _buildCourseBlock(
          context,
          number: '2️⃣',
          title: 'TNUSRB (Police SI/Constable)',
          englishTitle: 'TN Police Exam Prep',
          englishUrl: 'https://www.youtube.com/@TNPoliceExamPrep/playlists',
          tamilTitle: 'Uniform Force Tamil',
          tamilUrl: 'https://www.youtube.com/@UniformForce/playlists',
          notes: 'Reasoning, GK, psychology basics',
        ),
        _buildCourseBlock(
          context,
          number: '3️⃣',
          title: 'TRB / TET (Teaching)',
          englishTitle: 'TN TRB/TET Prep',
          englishUrl: 'https://www.youtube.com/@TRBcoaching/playlists',
          tamilTitle: 'TET in Tamil (FFTL / Teacher Exams)',
          tamilUrl: 'https://www.youtube.com/@TeacherExamsTamil/playlists',
          notes: 'Pedagogy, child psychology, GK',
        ),
        _buildCourseBlock(
          context,
          number: '4️⃣',
          title: 'UPSC (Central)',
          englishTitle: 'Unacademy UPSC / Amit Sengupta',
          englishUrl: 'https://www.youtube.com/@unacademyupsc/playlists',
          tamilTitle: 'UPSC Tamil (IAS Tamil)',
          tamilUrl: 'https://www.youtube.com/@IASTamil/playlists',
          notes: 'CSAT, GS, current affairs',
        ),
        _buildCourseBlock(
          context,
          number: '5️⃣',
          title: 'SSC CGL/CHSL',
          englishTitle: 'Adda247 SSC',
          englishUrl: 'https://www.youtube.com/@adda247/playlists',
          tamilTitle: 'SSC Tamil Prep',
          tamilUrl: 'https://www.youtube.com/@SSCTamil/playlists',
          notes: 'Quant, reasoning, English, GK',
        ),
        _buildCourseBlock(
          context,
          number: '6️⃣',
          title: 'Bank PO/Clerk (IBPS/SBI)',
          englishTitle: 'Bankers Way / Oliveboard',
          englishUrl: 'https://www.youtube.com/@bankersway/playlists',
          tamilTitle: 'Bank Exams Tamil',
          tamilUrl: 'https://www.youtube.com/@BankExamsTamil/playlists',
          notes: 'Quant, reasoning, English, banking awareness',
        ),
        _buildCourseBlock(
          context,
          number: '7️⃣',
          title: 'Railway RRB NTPC/Group D',
          englishTitle: 'Examपुर Railway',
          englishUrl: 'https://www.youtube.com/@exampur/playlists',
          tamilTitle: 'RRB Tamil Prep',
          tamilUrl: 'https://www.youtube.com/@RRBTamil/playlists',
          notes: 'Maths, reasoning, GK for RRB exams',
        ),
        _buildCourseBlock(
          context,
          number: '8️⃣',
          title: 'ESIC/EPFO/SSA',
          englishTitle: 'Adda247 ESIC/EPFO',
          englishUrl: 'https://www.youtube.com/@adda247/playlists',
          tamilTitle: 'EPFO Tamil Prep',
          tamilUrl: 'https://www.youtube.com/@EPFOTamil/playlists',
          notes: 'Social security, quant, reasoning, English',
        ),
        _buildCourseBlock(
          context,
          number: '9️⃣',
          title: 'LIC AAO/ADO',
          englishTitle: 'Bankers Way LIC',
          englishUrl: 'https://www.youtube.com/@bankersway/playlists',
          tamilTitle: 'LIC Exams Tamil',
          tamilUrl: 'https://www.youtube.com/@LICTamil/playlists',
          notes: 'Insurance awareness, quant, reasoning',
        ),
        _buildCourseBlock(
          context,
          number: '🔟',
          title: 'NABARD/SEBI/RBI Grade B',
          englishTitle: 'Anuj Jindal',
          englishUrl: 'https://www.youtube.com/@anujjindal/playlists',
          tamilTitle: 'RBI/SEBI Tamil',
          tamilUrl: 'https://www.youtube.com/@RBITamil/playlists',
          notes: 'ARd, ESI, finance, management, quant, GA',
        ),
        _buildCourseBlock(
          context,
          number: '11️⃣',
          title: 'SSC JE (Civil/Mech/Elec)',
          englishTitle: 'Civil Masters / Exampur JE',
          englishUrl: 'https://www.youtube.com/@CivilMaster/playlists',
          tamilTitle: 'SSC JE Tamil',
          tamilUrl: 'https://www.youtube.com/@SSCJETamil/playlists',
          notes: 'Tech + non-tech + aptitude',
        ),
        _buildCourseBlock(
          context,
          number: '12️⃣',
          title: 'GATE (CS/ECE/ME/EE)',
          englishTitle: 'Gate Smashers / NPTEL',
          englishUrl: 'https://www.youtube.com/@GateSmashers/playlists',
          tamilTitle: 'GATE Tamil',
          tamilUrl: 'https://www.youtube.com/@GATETamil/playlists',
          notes: 'Technical + aptitude + previous year',
        ),
        _buildCourseBlock(
          context,
          number: '13️⃣',
          title: 'CAT/XAT (for PSU management roles)',
          englishTitle: 'Handa Ka Funda',
          englishUrl: 'https://www.youtube.com/@handakafunda/playlists',
          tamilTitle: 'CAT Tamil Prep',
          tamilUrl: 'https://www.youtube.com/@CATTamil/playlists',
          notes: 'VARC, DILR, QA; useful for aptitude boosting',
        ),
        _buildCourseBlock(
          context,
          number: '14️⃣',
          title: 'Current Affairs (Daily/Monthly)',
          englishTitle: 'Study IQ – Daily CA',
          englishUrl: 'https://www.youtube.com/@StudyIQeducation/playlists',
          tamilTitle: 'Daily CA Tamil (FFTL/IAS Tamil)',
          tamilUrl: 'https://www.youtube.com/@IASTamil/playlists',
          notes: 'Essential for all TN & central exams',
        ),
        _buildCourseBlock(
          context,
          number: '15️⃣',
          title: 'Quant Crash Course',
          englishTitle: 'Takshzila Shikshak',
          englishUrl: 'https://www.youtube.com/@TakshzilaShikshak/playlists',
          tamilTitle: 'Quant Tamil (FFTL Aptitude)',
          tamilUrl: 'https://www.youtube.com/@FeelFreetoLearn/playlists',
          notes: 'Speed arithmetic, shortcuts, practice sets',
        ),
        _buildCourseBlock(
          context,
          number: '16️⃣',
          title: 'Reasoning Crash Course',
          englishTitle: 'Reasoning by Lokesh Sharma',
          englishUrl: 'https://www.youtube.com/@LokeshSharmaReasoning/playlists',
          tamilTitle: 'Reasoning Tamil (FFTL)',
          tamilUrl: 'https://www.youtube.com/@FeelFreetoLearn/playlists',
          notes: 'Puzzles, seating, syllogism, coding-decoding',
        ),
        _buildCourseBlock(
          context,
          number: '17️⃣',
          title: 'English Language for Exams',
          englishTitle: 'Adda247 English',
          englishUrl: 'https://www.youtube.com/@adda247/playlists',
          tamilTitle: 'English Grammar Tamil (Spoken Tutorials)',
          tamilUrl: 'https://www.youtube.com/@SpokenEnglishTamil/playlists',
          notes: 'Grammar, vocab, RC, cloze tests',
        ),
        _buildCourseBlock(
          context,
          number: '18️⃣',
          title: 'General Science (SSC/TNPSC/Police)',
          englishTitle: 'Exampur GS',
          englishUrl: 'https://www.youtube.com/@exampur/playlists',
          tamilTitle: 'Science Tamil (Ariviyal)',
          tamilUrl: 'https://www.youtube.com/@ariviyalintamil/playlists',
          notes: 'Physics, chem, bio basics for MCQs',
        ),
        _buildCourseBlock(
          context,
          number: '19️⃣',
          title: 'Indian History & Culture',
          englishTitle: 'Study IQ History',
          englishUrl: 'https://www.youtube.com/@StudyIQeducation/playlists',
          tamilTitle: 'History Tamil (Praveen/IAS Tamil)',
          tamilUrl: 'https://www.youtube.com/@IASTamil/playlists',
          notes: 'Ancient, medieval, modern, TN-specific',
        ),
        _buildCourseBlock(
          context,
          number: '20️⃣',
          title: 'Indian Geography',
          englishTitle: 'Geography by Amit Sengupta',
          englishUrl: 'https://www.youtube.com/@unacademyupsc/playlists',
          tamilTitle: 'Geography Tamil (IAS Tamil)',
          tamilUrl: 'https://www.youtube.com/@IASTamil/playlists',
          notes: 'Physical, economic, mapping',
        ),
        _buildCourseBlock(
          context,
          number: '21️⃣',
          title: 'Economy & Budget',
          englishTitle: 'Mrunal Economics',
          englishUrl: 'https://www.youtube.com/@mrunalpatel/playlists',
          tamilTitle: 'Economics Tamil',
          tamilUrl: 'https://www.youtube.com/@EconomicsTamil/playlists',
          notes: 'Macro, fiscal, monetary basics for GS',
        ),
        _buildCourseBlock(
          context,
          number: '22️⃣',
          title: 'Environment & Ecology',
          englishTitle: 'PMF IAS Environment',
          englishUrl: 'https://www.youtube.com/@pmfias/playlists',
          tamilTitle: 'Environment Tamil',
          tamilUrl: 'https://www.youtube.com/@EnvironmentTamil/playlists',
          notes: 'Climate, biodiversity, pollution',
        ),
        _buildCourseBlock(
          context,
          number: '23️⃣',
          title: 'Ethics & Integrity (UPSC/TNPSC Gr1)',
          englishTitle: 'OnlyIAS Ethics',
          englishUrl: 'https://www.youtube.com/@OnlyIAS/playlists',
          tamilTitle: 'Ethics Tamil (IAS Tamil)',
          tamilUrl: 'https://www.youtube.com/@IASTamil/playlists',
          notes: 'Case studies, values, integrity',
        ),
        _buildCourseBlock(
          context,
          number: '24️⃣',
          title: 'Essay & Descriptive Writing',
          englishTitle: 'Vision IAS Essay',
          englishUrl: 'https://www.youtube.com/@visionias/playlists',
          tamilTitle: 'Essay Tamil',
          tamilUrl: 'https://www.youtube.com/@EssayTamil/playlists',
          notes: 'Structure, examples, practice topics',
        ),
        _buildCourseBlock(
          context,
          number: '25️⃣',
          title: 'Interview Guidance (UPSC/TNPSC/Bank)',
          englishTitle: 'Drishti IAS Interview',
          englishUrl: 'https://www.youtube.com/@DrishtiIASHindi/playlists',
          tamilTitle: 'Interview Tips Tamil',
          tamilUrl: 'https://www.youtube.com/@InterviewTamil/playlists',
          notes: 'Mock interviews, posture, DAF basics',
        ),
        _buildCourseBlock(
          context,
          number: '26️⃣',
          title: 'Typing & Computer Awareness',
          englishTitle: 'Computer Awareness by Adda',
          englishUrl: 'https://www.youtube.com/@adda247/playlists',
          tamilTitle: 'Computer Basics Tamil',
          tamilUrl: 'https://www.youtube.com/@ComputerBasicsTamil/playlists',
          notes: 'MS Office, internet, basics for clerical exams',
        ),
        _buildCourseBlock(
          context,
          number: '27️⃣',
          title: 'Speed Tests & PYQs (All Exams)',
          englishTitle: 'KD Campus / Exampur Marathon',
          englishUrl: 'https://www.youtube.com/@exampur/playlists',
          tamilTitle: 'PYQ Marathon Tamil',
          tamilUrl: 'https://www.youtube.com/@PYQTamil/playlists',
          notes: 'Full-length practice + analysis',
        ),
        _buildCourseBlock(
          context,
          number: '28️⃣',
          title: 'CSAT Paper (UPSC)',
          englishTitle: 'Ravi Pagar CSAT',
          englishUrl: 'https://www.youtube.com/@RaviPagar/playlists',
          tamilTitle: 'CSAT Tamil (IAS Tamil)',
          tamilUrl: 'https://www.youtube.com/@IASTamil/playlists',
          notes: 'Aptitude + comprehension for UPSC prelims',
        ),
        _buildCourseBlock(
          context,
          number: '29️⃣',
          title: 'TN Current Affairs (Monthly Compilation)',
          englishTitle: 'Shankar IAS Monthly CA',
          englishUrl: 'https://www.youtube.com/@ShankarIASAcademy/playlists',
          tamilTitle: 'TN Monthly CA Tamil',
          tamilUrl: 'https://www.youtube.com/@TamilCurrentAffairs/playlists',
          notes: 'State-specific news, schemes, budget',
        ),
        _buildCourseBlock(
          context,
          number: '30️⃣',
          title: 'Exam Strategy & Planner',
          englishTitle: 'Officer’s IAS Academy',
          englishUrl: 'https://www.youtube.com/@OfficersIASAcademy/playlists',
          tamilTitle: 'Strategy Tamil (FFTL/IAS Tamil)',
          tamilUrl: 'https://www.youtube.com/@IASTamil/playlists',
          notes: 'Timetable, booklist, daily routine',
        ),
      ];

  Widget _buildCourseBlock(
    BuildContext context, {
    required String number,
    required String title,
    required String englishTitle,
    required String englishUrl,
    required String tamilTitle,
    required String tamilUrl,
    required String notes,
  }) {
    return Container(
      margin: const EdgeInsets.only(bottom: 16),
      padding: const EdgeInsets.all(14),
      decoration: BoxDecoration(
        color: Colors.white.withOpacity(0.08),
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: Colors.white24),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            '$number $title',
            style: const TextStyle(
              color: Colors.white,
              fontWeight: FontWeight.w700,
              fontSize: 14,
            ),
          ),
          const SizedBox(height: 8),
          _buildLinkTile(context, '🇬🇧 English', englishTitle, englishUrl),
          _buildLinkTile(context, '🇮🇳 Tamil', tamilTitle, tamilUrl),
          const SizedBox(height: 6),
          Text(
            '✔️ $notes',
            style: TextStyle(
              color: Colors.white.withOpacity(0.8),
              fontSize: 12,
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildLinkTile(
    BuildContext context,
    String language,
    String title,
    String url,
  ) {
    return ListTile(
      contentPadding: EdgeInsets.zero,
      dense: true,
      leading: Text(
        language,
        style: const TextStyle(color: Colors.white, fontWeight: FontWeight.w600),
      ),
      title: Text(
        title,
        style: const TextStyle(color: Colors.white),
      ),
      trailing: const Icon(Icons.open_in_new, color: Colors.white70),
      onTap: () => _openLink(context, url),
    );
  }

  Future<void> _openLink(BuildContext context, String url) async {
    final uri = Uri.parse(url);
    final launched = await launchUrl(
      uri,
      mode: LaunchMode.externalApplication,
    );
    if (!launched && context.mounted) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Could not open link')),
      );
    }
  }
}
