import 'package:firebase_core/firebase_core.dart';

/// Placeholder Firebase configuration.
/// Replace this file with the one generated by `flutterfire configure`
/// (or fill the fields below) before running the app with Firebase enabled.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform => const FirebaseOptions(
        apiKey: 'ADD_API_KEY',
        appId: 'ADD_APP_ID',
        messagingSenderId: 'ADD_SENDER_ID',
        projectId: 'ADD_PROJECT_ID',
      );
}
